//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendCheck472.EncSyncService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestInfo2", Namespace="http://schemas.datacontract.org/2004/07/NavService")]
    [System.SerializableAttribute()]
    public partial class RequestInfo2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientVerificationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstimatedCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstimatedSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan EstimatedTimeToWaitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VesselNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientVerificationCode {
            get {
                return this.ClientVerificationCodeField;
            }
            set {
                if ((this.ClientVerificationCodeField.Equals(value) != true)) {
                    this.ClientVerificationCodeField = value;
                    this.RaisePropertyChanged("ClientVerificationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstimatedCount {
            get {
                return this.EstimatedCountField;
            }
            set {
                if ((this.EstimatedCountField.Equals(value) != true)) {
                    this.EstimatedCountField = value;
                    this.RaisePropertyChanged("EstimatedCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstimatedSize {
            get {
                return this.EstimatedSizeField;
            }
            set {
                if ((this.EstimatedSizeField.Equals(value) != true)) {
                    this.EstimatedSizeField = value;
                    this.RaisePropertyChanged("EstimatedSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan EstimatedTimeToWait {
            get {
                return this.EstimatedTimeToWaitField;
            }
            set {
                if ((this.EstimatedTimeToWaitField.Equals(value) != true)) {
                    this.EstimatedTimeToWaitField = value;
                    this.RaisePropertyChanged("EstimatedTimeToWait");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestGUID {
            get {
                return this.RequestGUIDField;
            }
            set {
                if ((this.RequestGUIDField.Equals(value) != true)) {
                    this.RequestGUIDField = value;
                    this.RaisePropertyChanged("RequestGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VesselName {
            get {
                return this.VesselNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VesselNameField, value) != true)) {
                    this.VesselNameField = value;
                    this.RaisePropertyChanged("VesselName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestInfo3", Namespace="http://schemas.datacontract.org/2004/07/NavService")]
    [System.SerializableAttribute()]
    public partial class RequestInfo3 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientVerificationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstimatedCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstimatedSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan EstimatedTimeToWaitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReleaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReleaseWeekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReleaseYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VesselNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientVerificationCode {
            get {
                return this.ClientVerificationCodeField;
            }
            set {
                if ((this.ClientVerificationCodeField.Equals(value) != true)) {
                    this.ClientVerificationCodeField = value;
                    this.RaisePropertyChanged("ClientVerificationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataServer {
            get {
                return this.DataServerField;
            }
            set {
                if ((object.ReferenceEquals(this.DataServerField, value) != true)) {
                    this.DataServerField = value;
                    this.RaisePropertyChanged("DataServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstimatedCount {
            get {
                return this.EstimatedCountField;
            }
            set {
                if ((this.EstimatedCountField.Equals(value) != true)) {
                    this.EstimatedCountField = value;
                    this.RaisePropertyChanged("EstimatedCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstimatedSize {
            get {
                return this.EstimatedSizeField;
            }
            set {
                if ((this.EstimatedSizeField.Equals(value) != true)) {
                    this.EstimatedSizeField = value;
                    this.RaisePropertyChanged("EstimatedSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan EstimatedTimeToWait {
            get {
                return this.EstimatedTimeToWaitField;
            }
            set {
                if ((this.EstimatedTimeToWaitField.Equals(value) != true)) {
                    this.EstimatedTimeToWaitField = value;
                    this.RaisePropertyChanged("EstimatedTimeToWait");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((this.ReleaseDateField.Equals(value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReleaseWeek {
            get {
                return this.ReleaseWeekField;
            }
            set {
                if ((this.ReleaseWeekField.Equals(value) != true)) {
                    this.ReleaseWeekField = value;
                    this.RaisePropertyChanged("ReleaseWeek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReleaseYear {
            get {
                return this.ReleaseYearField;
            }
            set {
                if ((this.ReleaseYearField.Equals(value) != true)) {
                    this.ReleaseYearField = value;
                    this.RaisePropertyChanged("ReleaseYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestGUID {
            get {
                return this.RequestGUIDField;
            }
            set {
                if ((this.RequestGUIDField.Equals(value) != true)) {
                    this.RequestGUIDField = value;
                    this.RaisePropertyChanged("RequestGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VesselName {
            get {
                return this.VesselNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VesselNameField, value) != true)) {
                    this.VesselNameField = value;
                    this.RaisePropertyChanged("VesselName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestInfo4", Namespace="http://schemas.datacontract.org/2004/07/NavService")]
    [System.SerializableAttribute()]
    public partial class RequestInfo4 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientVerificationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstimatedCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstimatedSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan EstimatedTimeToWaitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreRegisterOemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReleaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReleaseWeekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReleaseYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VesselNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientVerificationCode {
            get {
                return this.ClientVerificationCodeField;
            }
            set {
                if ((this.ClientVerificationCodeField.Equals(value) != true)) {
                    this.ClientVerificationCodeField = value;
                    this.RaisePropertyChanged("ClientVerificationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataServer {
            get {
                return this.DataServerField;
            }
            set {
                if ((object.ReferenceEquals(this.DataServerField, value) != true)) {
                    this.DataServerField = value;
                    this.RaisePropertyChanged("DataServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstimatedCount {
            get {
                return this.EstimatedCountField;
            }
            set {
                if ((this.EstimatedCountField.Equals(value) != true)) {
                    this.EstimatedCountField = value;
                    this.RaisePropertyChanged("EstimatedCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstimatedSize {
            get {
                return this.EstimatedSizeField;
            }
            set {
                if ((this.EstimatedSizeField.Equals(value) != true)) {
                    this.EstimatedSizeField = value;
                    this.RaisePropertyChanged("EstimatedSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan EstimatedTimeToWait {
            get {
                return this.EstimatedTimeToWaitField;
            }
            set {
                if ((this.EstimatedTimeToWaitField.Equals(value) != true)) {
                    this.EstimatedTimeToWaitField = value;
                    this.RaisePropertyChanged("EstimatedTimeToWait");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreRegisterOem {
            get {
                return this.PreRegisterOemField;
            }
            set {
                if ((object.ReferenceEquals(this.PreRegisterOemField, value) != true)) {
                    this.PreRegisterOemField = value;
                    this.RaisePropertyChanged("PreRegisterOem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((this.ReleaseDateField.Equals(value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReleaseWeek {
            get {
                return this.ReleaseWeekField;
            }
            set {
                if ((this.ReleaseWeekField.Equals(value) != true)) {
                    this.ReleaseWeekField = value;
                    this.RaisePropertyChanged("ReleaseWeek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReleaseYear {
            get {
                return this.ReleaseYearField;
            }
            set {
                if ((this.ReleaseYearField.Equals(value) != true)) {
                    this.ReleaseYearField = value;
                    this.RaisePropertyChanged("ReleaseYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestGUID {
            get {
                return this.RequestGUIDField;
            }
            set {
                if ((this.RequestGUIDField.Equals(value) != true)) {
                    this.RequestGUIDField = value;
                    this.RaisePropertyChanged("RequestGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VesselName {
            get {
                return this.VesselNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VesselNameField, value) != true)) {
                    this.VesselNameField = value;
                    this.RaisePropertyChanged("VesselName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestInfo5", Namespace="http://schemas.datacontract.org/2004/07/NavService")]
    [System.SerializableAttribute()]
    public partial class RequestInfo5 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientVerificationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstimatedCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstimatedSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan EstimatedTimeToWaitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExportS63Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExportSENCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreRegisterOemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReleaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReleaseWeekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReleaseYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeOfCellsUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VesselNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientVerificationCode {
            get {
                return this.ClientVerificationCodeField;
            }
            set {
                if ((this.ClientVerificationCodeField.Equals(value) != true)) {
                    this.ClientVerificationCodeField = value;
                    this.RaisePropertyChanged("ClientVerificationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataServer {
            get {
                return this.DataServerField;
            }
            set {
                if ((object.ReferenceEquals(this.DataServerField, value) != true)) {
                    this.DataServerField = value;
                    this.RaisePropertyChanged("DataServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstimatedCount {
            get {
                return this.EstimatedCountField;
            }
            set {
                if ((this.EstimatedCountField.Equals(value) != true)) {
                    this.EstimatedCountField = value;
                    this.RaisePropertyChanged("EstimatedCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstimatedSize {
            get {
                return this.EstimatedSizeField;
            }
            set {
                if ((this.EstimatedSizeField.Equals(value) != true)) {
                    this.EstimatedSizeField = value;
                    this.RaisePropertyChanged("EstimatedSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan EstimatedTimeToWait {
            get {
                return this.EstimatedTimeToWaitField;
            }
            set {
                if ((this.EstimatedTimeToWaitField.Equals(value) != true)) {
                    this.EstimatedTimeToWaitField = value;
                    this.RaisePropertyChanged("EstimatedTimeToWait");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExportS63 {
            get {
                return this.ExportS63Field;
            }
            set {
                if ((this.ExportS63Field.Equals(value) != true)) {
                    this.ExportS63Field = value;
                    this.RaisePropertyChanged("ExportS63");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExportSENC {
            get {
                return this.ExportSENCField;
            }
            set {
                if ((this.ExportSENCField.Equals(value) != true)) {
                    this.ExportSENCField = value;
                    this.RaisePropertyChanged("ExportSENC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreRegisterOem {
            get {
                return this.PreRegisterOemField;
            }
            set {
                if ((object.ReferenceEquals(this.PreRegisterOemField, value) != true)) {
                    this.PreRegisterOemField = value;
                    this.RaisePropertyChanged("PreRegisterOem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((this.ReleaseDateField.Equals(value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReleaseWeek {
            get {
                return this.ReleaseWeekField;
            }
            set {
                if ((this.ReleaseWeekField.Equals(value) != true)) {
                    this.ReleaseWeekField = value;
                    this.RaisePropertyChanged("ReleaseWeek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReleaseYear {
            get {
                return this.ReleaseYearField;
            }
            set {
                if ((this.ReleaseYearField.Equals(value) != true)) {
                    this.ReleaseYearField = value;
                    this.RaisePropertyChanged("ReleaseYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestGUID {
            get {
                return this.RequestGUIDField;
            }
            set {
                if ((this.RequestGUIDField.Equals(value) != true)) {
                    this.RequestGUIDField = value;
                    this.RaisePropertyChanged("RequestGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SizeOfCellsUpdated {
            get {
                return this.SizeOfCellsUpdatedField;
            }
            set {
                if ((this.SizeOfCellsUpdatedField.Equals(value) != true)) {
                    this.SizeOfCellsUpdatedField = value;
                    this.RaisePropertyChanged("SizeOfCellsUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VesselName {
            get {
                return this.VesselNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VesselNameField, value) != true)) {
                    this.VesselNameField = value;
                    this.RaisePropertyChanged("VesselName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestArguments", Namespace="http://schemas.datacontract.org/2004/07/NavService")]
    [System.SerializableAttribute()]
    public partial class RequestArguments : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BackupFolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BackupHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BytesToSaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] InventoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLazyOfflineRequestProcessingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastBackedupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoggedInUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NavBoxIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NavBoxSwVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NavSyncVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OSVersionCallerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] OffLineRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OpAreaCrcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdentifierField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BackupFolder {
            get {
                return this.BackupFolderField;
            }
            set {
                if ((object.ReferenceEquals(this.BackupFolderField, value) != true)) {
                    this.BackupFolderField = value;
                    this.RaisePropertyChanged("BackupFolder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BackupHost {
            get {
                return this.BackupHostField;
            }
            set {
                if ((object.ReferenceEquals(this.BackupHostField, value) != true)) {
                    this.BackupHostField = value;
                    this.RaisePropertyChanged("BackupHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BytesToSave {
            get {
                return this.BytesToSaveField;
            }
            set {
                if ((this.BytesToSaveField.Equals(value) != true)) {
                    this.BytesToSaveField = value;
                    this.RaisePropertyChanged("BytesToSave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataServer {
            get {
                return this.DataServerField;
            }
            set {
                if ((object.ReferenceEquals(this.DataServerField, value) != true)) {
                    this.DataServerField = value;
                    this.RaisePropertyChanged("DataServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Inventory {
            get {
                return this.InventoryField;
            }
            set {
                if ((object.ReferenceEquals(this.InventoryField, value) != true)) {
                    this.InventoryField = value;
                    this.RaisePropertyChanged("Inventory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLazyOfflineRequestProcessing {
            get {
                return this.IsLazyOfflineRequestProcessingField;
            }
            set {
                if ((this.IsLazyOfflineRequestProcessingField.Equals(value) != true)) {
                    this.IsLazyOfflineRequestProcessingField = value;
                    this.RaisePropertyChanged("IsLazyOfflineRequestProcessing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastBackedup {
            get {
                return this.LastBackedupField;
            }
            set {
                if ((this.LastBackedupField.Equals(value) != true)) {
                    this.LastBackedupField = value;
                    this.RaisePropertyChanged("LastBackedup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoggedInUser {
            get {
                return this.LoggedInUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LoggedInUserField, value) != true)) {
                    this.LoggedInUserField = value;
                    this.RaisePropertyChanged("LoggedInUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NavBoxId {
            get {
                return this.NavBoxIdField;
            }
            set {
                if ((object.ReferenceEquals(this.NavBoxIdField, value) != true)) {
                    this.NavBoxIdField = value;
                    this.RaisePropertyChanged("NavBoxId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NavBoxSwVersion {
            get {
                return this.NavBoxSwVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.NavBoxSwVersionField, value) != true)) {
                    this.NavBoxSwVersionField = value;
                    this.RaisePropertyChanged("NavBoxSwVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NavSyncVersion {
            get {
                return this.NavSyncVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.NavSyncVersionField, value) != true)) {
                    this.NavSyncVersionField = value;
                    this.RaisePropertyChanged("NavSyncVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OSVersionCaller {
            get {
                return this.OSVersionCallerField;
            }
            set {
                if ((object.ReferenceEquals(this.OSVersionCallerField, value) != true)) {
                    this.OSVersionCallerField = value;
                    this.RaisePropertyChanged("OSVersionCaller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] OffLineRequest {
            get {
                return this.OffLineRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.OffLineRequestField, value) != true)) {
                    this.OffLineRequestField = value;
                    this.RaisePropertyChanged("OffLineRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpAreaCrc {
            get {
                return this.OpAreaCrcField;
            }
            set {
                if ((this.OpAreaCrcField.Equals(value) != true)) {
                    this.OpAreaCrcField = value;
                    this.RaisePropertyChanged("OpAreaCrc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserIdentifier {
            get {
                return this.UserIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdentifierField, value) != true)) {
                    this.UserIdentifierField = value;
                    this.RaisePropertyChanged("UserIdentifier");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportInfo", Namespace="http://schemas.datacontract.org/2004/07/NavService")]
    [System.SerializableAttribute()]
    public partial class ReportInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatabaseVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfNewENCsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfNewIssuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfPicTxtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfUpdatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UpdateSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VesselNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatabaseVersion {
            get {
                return this.DatabaseVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.DatabaseVersionField, value) != true)) {
                    this.DatabaseVersionField = value;
                    this.RaisePropertyChanged("DatabaseVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfNewENCs {
            get {
                return this.NumberOfNewENCsField;
            }
            set {
                if ((this.NumberOfNewENCsField.Equals(value) != true)) {
                    this.NumberOfNewENCsField = value;
                    this.RaisePropertyChanged("NumberOfNewENCs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfNewIssues {
            get {
                return this.NumberOfNewIssuesField;
            }
            set {
                if ((this.NumberOfNewIssuesField.Equals(value) != true)) {
                    this.NumberOfNewIssuesField = value;
                    this.RaisePropertyChanged("NumberOfNewIssues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfPicTxt {
            get {
                return this.NumberOfPicTxtField;
            }
            set {
                if ((this.NumberOfPicTxtField.Equals(value) != true)) {
                    this.NumberOfPicTxtField = value;
                    this.RaisePropertyChanged("NumberOfPicTxt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfUpdates {
            get {
                return this.NumberOfUpdatesField;
            }
            set {
                if ((this.NumberOfUpdatesField.Equals(value) != true)) {
                    this.NumberOfUpdatesField = value;
                    this.RaisePropertyChanged("NumberOfUpdates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestGUID {
            get {
                return this.RequestGUIDField;
            }
            set {
                if ((this.RequestGUIDField.Equals(value) != true)) {
                    this.RequestGUIDField = value;
                    this.RaisePropertyChanged("RequestGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdateSize {
            get {
                return this.UpdateSizeField;
            }
            set {
                if ((this.UpdateSizeField.Equals(value) != true)) {
                    this.UpdateSizeField = value;
                    this.RaisePropertyChanged("UpdateSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserIdentifier {
            get {
                return this.UserIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdentifierField, value) != true)) {
                    this.UserIdentifierField = value;
                    this.RaisePropertyChanged("UserIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VesselName {
            get {
                return this.VesselNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VesselNameField, value) != true)) {
                    this.VesselNameField = value;
                    this.RaisePropertyChanged("VesselName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileDescription", Namespace="http://schemas.datacontract.org/2004/07/NavService")]
    [System.SerializableAttribute()]
    public partial class FileDescription : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FileSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Crc {
            get {
                return this.CrcField;
            }
            set {
                if ((this.CrcField.Equals(value) != true)) {
                    this.CrcField = value;
                    this.RaisePropertyChanged("Crc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((this.FileSizeField.Equals(value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFileIdResult", Namespace="http://schemas.datacontract.org/2004/07/NavService")]
    public enum GetFileIdResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Succeeded = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyHasNewVersion = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NavStickIsNotRegistered = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileIdInfo", Namespace="http://schemas.datacontract.org/2004/07/NavService")]
    [System.SerializableAttribute()]
    public partial class FileIdInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsObsoleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsObsolete {
            get {
                return this.IsObsoleteField;
            }
            set {
                if ((this.IsObsoleteField.Equals(value) != true)) {
                    this.IsObsoleteField = value;
                    this.RaisePropertyChanged("IsObsolete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReinitializeDatabaseResult", Namespace="http://schemas.datacontract.org/2004/07/NavService")]
    public enum ReinitializeDatabaseResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Succeded = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NavStickNotRegistered = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternalDBFile", Namespace="http://schemas.datacontract.org/2004/07/NavService")]
    [System.SerializableAttribute()]
    public partial class InternalDBFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Crc {
            get {
                return this.CrcField;
            }
            set {
                if ((this.CrcField.Equals(value) != true)) {
                    this.CrcField = value;
                    this.RaisePropertyChanged("Crc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((this.FileSizeField.Equals(value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EncSyncService.IENCSync")]
    public interface IENCSync {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/Request2", ReplyAction="http://tempuri.org/IENCSync/Request2Response")]
        SendCheck472.EncSyncService.RequestInfo2 Request2(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/Request3", ReplyAction="http://tempuri.org/IENCSync/Request3Response")]
        SendCheck472.EncSyncService.RequestInfo2 Request3(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/Request4", ReplyAction="http://tempuri.org/IENCSync/Request4Response")]
        SendCheck472.EncSyncService.RequestInfo3 Request4(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion, string dataServer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/Request5", ReplyAction="http://tempuri.org/IENCSync/Request5Response")]
        SendCheck472.EncSyncService.RequestInfo4 Request5(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion, string dataServer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/Request6", ReplyAction="http://tempuri.org/IENCSync/Request6Response")]
        SendCheck472.EncSyncService.RequestInfo5 Request6(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion, string dataServer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/Request7", ReplyAction="http://tempuri.org/IENCSync/Request7Response")]
        SendCheck472.EncSyncService.RequestInfo5 Request7(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion, string dataServer, string loggedInUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/Request8", ReplyAction="http://tempuri.org/IENCSync/Request8Response")]
        SendCheck472.EncSyncService.RequestInfo5 Request8(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion, string dataServer, string loggedInUser, byte[] navtrackerOfflineData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/Request9", ReplyAction="http://tempuri.org/IENCSync/Request9Response")]
        SendCheck472.EncSyncService.RequestInfo5 Request9(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion, string dataServer, string loggedInUser, byte[] navtrackerOfflineData, long bytesToCompress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/Request10", ReplyAction="http://tempuri.org/IENCSync/Request10Response")]
        SendCheck472.EncSyncService.RequestInfo5 Request10(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion, string dataServer, string loggedInUser, byte[] offLineRequest, long bytesToSave, System.Nullable<System.DateTime> lastBackedup, string backupFolder, string backupHost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/Request11", ReplyAction="http://tempuri.org/IENCSync/Request11Response")]
        SendCheck472.EncSyncService.RequestInfo5 Request11(SendCheck472.EncSyncService.RequestArguments arguments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/CloseAndReport2", ReplyAction="http://tempuri.org/IENCSync/CloseAndReport2Response")]
        string CloseAndReport2(SendCheck472.EncSyncService.ReportInfo reportInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/GetCurrTimeUtc", ReplyAction="http://tempuri.org/IENCSync/GetCurrTimeUtcResponse")]
        System.DateTime GetCurrTimeUtc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/GetImoNoFromVesseldentifier", ReplyAction="http://tempuri.org/IENCSync/GetImoNoFromVesseldentifierResponse")]
        int GetImoNoFromVesseldentifier(string userIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/IsValidNavStick", ReplyAction="http://tempuri.org/IENCSync/IsValidNavStickResponse")]
        bool IsValidNavStick(string navstick_serial_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/IsValidNavStick2", ReplyAction="http://tempuri.org/IENCSync/IsValidNavStick2Response")]
        bool IsValidNavStick2(out bool bReInitializeAllowed, string navstick_serial_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/ReportDirectoryContent", ReplyAction="http://tempuri.org/IENCSync/ReportDirectoryContentResponse")]
        bool ReportDirectoryContent(int imoNo, string clientSoftware, string topDirectory, byte[] compressedDirectoryContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/Refill", ReplyAction="http://tempuri.org/IENCSync/RefillResponse")]
        SendCheck472.EncSyncService.RequestInfo5 Refill(out bool reduced, string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion, string dataServer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/GetFileId", ReplyAction="http://tempuri.org/IENCSync/GetFileIdResponse")]
        SendCheck472.EncSyncService.GetFileIdResult GetFileId(out SendCheck472.EncSyncService.FileIdInfo fileIdInfo, string navSyncVersion, string userIdentifier, SendCheck472.EncSyncService.FileDescription newFile, SendCheck472.EncSyncService.FileDescription[] existingFiles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/ReportExternalFileImport", ReplyAction="http://tempuri.org/IENCSync/ReportExternalFileImportResponse")]
        void ReportExternalFileImport(string navSyncVersion, string userIdentifier, int[] fileIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/GetInternalDBFiles", ReplyAction="http://tempuri.org/IENCSync/GetInternalDBFilesResponse")]
        SendCheck472.EncSyncService.ReinitializeDatabaseResult GetInternalDBFiles(out SendCheck472.EncSyncService.InternalDBFile[] files, out string producerCode, string navSyncVersion, string navStickSerialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/GetDataUpdateMaxSize", ReplyAction="http://tempuri.org/IENCSync/GetDataUpdateMaxSizeResponse")]
        int GetDataUpdateMaxSize(string userIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/GeneratePdf", ReplyAction="http://tempuri.org/IENCSync/GeneratePdfResponse")]
        bool GeneratePdf(System.Guid guid, int patchSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/GeneratePdf2", ReplyAction="http://tempuri.org/IENCSync/GeneratePdf2Response")]
        byte[] GeneratePdf2(System.Guid guid, int patchSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENCSync/TimeoutTestMethod", ReplyAction="http://tempuri.org/IENCSync/TimeoutTestMethodResponse")]
        bool TimeoutTestMethod(System.TimeSpan timeout);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IENCSyncChannel : SendCheck472.EncSyncService.IENCSync, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ENCSyncClient : System.ServiceModel.ClientBase<SendCheck472.EncSyncService.IENCSync>, SendCheck472.EncSyncService.IENCSync {
        
        public ENCSyncClient() {
        }
        
        public ENCSyncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ENCSyncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ENCSyncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ENCSyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SendCheck472.EncSyncService.RequestInfo2 Request2(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc) {
            return base.Channel.Request2(navSyncVersion, userIdentifier, inventory, opAreaCrc);
        }
        
        public SendCheck472.EncSyncService.RequestInfo2 Request3(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion) {
            return base.Channel.Request3(navSyncVersion, userIdentifier, inventory, opAreaCrc, navBoxId, navBoxSwVersion);
        }
        
        public SendCheck472.EncSyncService.RequestInfo3 Request4(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion, string dataServer) {
            return base.Channel.Request4(navSyncVersion, userIdentifier, inventory, opAreaCrc, navBoxId, navBoxSwVersion, dataServer);
        }
        
        public SendCheck472.EncSyncService.RequestInfo4 Request5(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion, string dataServer) {
            return base.Channel.Request5(navSyncVersion, userIdentifier, inventory, opAreaCrc, navBoxId, navBoxSwVersion, dataServer);
        }
        
        public SendCheck472.EncSyncService.RequestInfo5 Request6(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion, string dataServer) {
            return base.Channel.Request6(navSyncVersion, userIdentifier, inventory, opAreaCrc, navBoxId, navBoxSwVersion, dataServer);
        }
        
        public SendCheck472.EncSyncService.RequestInfo5 Request7(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion, string dataServer, string loggedInUser) {
            return base.Channel.Request7(navSyncVersion, userIdentifier, inventory, opAreaCrc, navBoxId, navBoxSwVersion, dataServer, loggedInUser);
        }
        
        public SendCheck472.EncSyncService.RequestInfo5 Request8(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion, string dataServer, string loggedInUser, byte[] navtrackerOfflineData) {
            return base.Channel.Request8(navSyncVersion, userIdentifier, inventory, opAreaCrc, navBoxId, navBoxSwVersion, dataServer, loggedInUser, navtrackerOfflineData);
        }
        
        public SendCheck472.EncSyncService.RequestInfo5 Request9(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion, string dataServer, string loggedInUser, byte[] navtrackerOfflineData, long bytesToCompress) {
            return base.Channel.Request9(navSyncVersion, userIdentifier, inventory, opAreaCrc, navBoxId, navBoxSwVersion, dataServer, loggedInUser, navtrackerOfflineData, bytesToCompress);
        }
        
        public SendCheck472.EncSyncService.RequestInfo5 Request10(string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion, string dataServer, string loggedInUser, byte[] offLineRequest, long bytesToSave, System.Nullable<System.DateTime> lastBackedup, string backupFolder, string backupHost) {
            return base.Channel.Request10(navSyncVersion, userIdentifier, inventory, opAreaCrc, navBoxId, navBoxSwVersion, dataServer, loggedInUser, offLineRequest, bytesToSave, lastBackedup, backupFolder, backupHost);
        }
        
        public SendCheck472.EncSyncService.RequestInfo5 Request11(SendCheck472.EncSyncService.RequestArguments arguments) {
            return base.Channel.Request11(arguments);
        }
        
        public string CloseAndReport2(SendCheck472.EncSyncService.ReportInfo reportInfo) {
            return base.Channel.CloseAndReport2(reportInfo);
        }
        
        public System.DateTime GetCurrTimeUtc() {
            return base.Channel.GetCurrTimeUtc();
        }
        
        public int GetImoNoFromVesseldentifier(string userIdentifier) {
            return base.Channel.GetImoNoFromVesseldentifier(userIdentifier);
        }
        
        public bool IsValidNavStick(string navstick_serial_number) {
            return base.Channel.IsValidNavStick(navstick_serial_number);
        }
        
        public bool IsValidNavStick2(out bool bReInitializeAllowed, string navstick_serial_number) {
            return base.Channel.IsValidNavStick2(out bReInitializeAllowed, navstick_serial_number);
        }
        
        public bool ReportDirectoryContent(int imoNo, string clientSoftware, string topDirectory, byte[] compressedDirectoryContent) {
            return base.Channel.ReportDirectoryContent(imoNo, clientSoftware, topDirectory, compressedDirectoryContent);
        }
        
        public SendCheck472.EncSyncService.RequestInfo5 Refill(out bool reduced, string navSyncVersion, string userIdentifier, byte[] inventory, int opAreaCrc, string navBoxId, string navBoxSwVersion, string dataServer) {
            return base.Channel.Refill(out reduced, navSyncVersion, userIdentifier, inventory, opAreaCrc, navBoxId, navBoxSwVersion, dataServer);
        }
        
        public SendCheck472.EncSyncService.GetFileIdResult GetFileId(out SendCheck472.EncSyncService.FileIdInfo fileIdInfo, string navSyncVersion, string userIdentifier, SendCheck472.EncSyncService.FileDescription newFile, SendCheck472.EncSyncService.FileDescription[] existingFiles) {
            return base.Channel.GetFileId(out fileIdInfo, navSyncVersion, userIdentifier, newFile, existingFiles);
        }
        
        public void ReportExternalFileImport(string navSyncVersion, string userIdentifier, int[] fileIds) {
            base.Channel.ReportExternalFileImport(navSyncVersion, userIdentifier, fileIds);
        }
        
        public SendCheck472.EncSyncService.ReinitializeDatabaseResult GetInternalDBFiles(out SendCheck472.EncSyncService.InternalDBFile[] files, out string producerCode, string navSyncVersion, string navStickSerialNumber) {
            return base.Channel.GetInternalDBFiles(out files, out producerCode, navSyncVersion, navStickSerialNumber);
        }
        
        public int GetDataUpdateMaxSize(string userIdentifier) {
            return base.Channel.GetDataUpdateMaxSize(userIdentifier);
        }
        
        public bool GeneratePdf(System.Guid guid, int patchSize) {
            return base.Channel.GeneratePdf(guid, patchSize);
        }
        
        public byte[] GeneratePdf2(System.Guid guid, int patchSize) {
            return base.Channel.GeneratePdf2(guid, patchSize);
        }
        
        public bool TimeoutTestMethod(System.TimeSpan timeout) {
            return base.Channel.TimeoutTestMethod(timeout);
        }
    }
}
